// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_OAVDH7tHXinYMuSBKd3UpCsVYvSLkA',
    appId: '1:368058102645:web:9db7242a94916e4242593c',
    messagingSenderId: '368058102645',
    projectId: 'inventryapp-93d6e',
    authDomain: 'inventryapp-93d6e.firebaseapp.com',
    storageBucket: 'inventryapp-93d6e.firebasestorage.app',
    measurementId: 'G-Y1KH61ZM78',
    databaseURL: 'https://inventryapp-93d6e-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1seW438yLHzs5xkYu5dJT1YN9eJcPe54',
    appId: '1:368058102645:android:7272bdd71192609842593c',
    messagingSenderId: '368058102645',
    projectId: 'inventryapp-93d6e',
    storageBucket: 'inventryapp-93d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqcSqM8xXx51SRWZ261LUfP3qqnKtHVM',
    appId: '1:368058102645:ios:cc109636a2e344fb42593c',
    messagingSenderId: '368058102645',
    projectId: 'inventryapp-93d6e',
    storageBucket: 'inventryapp-93d6e.firebasestorage.app',
    iosBundleId: 'com.example.graphicslabinventoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqcSqM8xXx51SRWZ261LUfP3qqnKtHVM',
    appId: '1:368058102645:ios:cc109636a2e344fb42593c',
    messagingSenderId: '368058102645',
    projectId: 'inventryapp-93d6e',
    storageBucket: 'inventryapp-93d6e.firebasestorage.app',
    iosBundleId: 'com.example.graphicslabinventoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8_OAVDH7tHXinYMuSBKd3UpCsVYvSLkA',
    appId: '1:368058102645:web:0907155ffc4a20b942593c',
    messagingSenderId: '368058102645',
    projectId: 'inventryapp-93d6e',
    authDomain: 'inventryapp-93d6e.firebaseapp.com',
    storageBucket: 'inventryapp-93d6e.firebasestorage.app',
    measurementId: 'G-JRQDLYS4M4',
  );
}
